apiVersion: v1
kind: Service
metadata:
  name: tbweb-svc-prod
  labels:
    app: tbweb-prod
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: tbweb-prod
---
apiVersion: v1
kind: Service
metadata:
  name: tbweb-svc-dev
  labels:
    app: tbweb-dev
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: tbweb-dev
---
apiVersion: v1
kind: Service
metadata:
  name: tbweb-svc-test
  labels:
    app: tbweb-test
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: tbweb-test
---
apiVersion: v1
kind: Service
metadata:
  name: tbweb-svc-beta
  labels:
    app: tbweb-beta
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: tbweb-beta
