apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: tbweb-deployment
  labels:
    app: tbweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tbweb
  template:
    metadata:
      labels:
        app: tbweb
    spec:
      securityContext:
        capabilities:
            add:
            - SYS_ADMIN
            - DAC_READ_SEARCH
            - MKNOD
        privileged: true
      containers:
      - name: tbweb
        image: theballweb:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
#        - containerPort: 443
#        volumeMounts:
#        - name: azureconf
#          mountPath: /Z
        env:
        -   name: CoreFileShareAccountName
            valueFrom:
                secretKeyRef:
                    name: tbdevtest-secret
                    key: azurestorageaccountname
        -   name: CoreFileShareAccountKey
            valueFrom:
                secretKeyRef:
                    name: tbdevtest-secret
                    key: azurestorageaccountkey
        -   name: TBCertificatePassword
            valueFrom:
                secretKeyRef:
                    name: tbdevtest-secret
                    key: certpassword
#      volumes:
#      -  name: azureconf
#         azureFile:
#           secretName: tbdevtest-secret
#           shareName: tbdevtest
#           readOnly: false
