apiVersion: v1
kind: Service
metadata:
  name: tbweb-svc
  labels:
    app: tbweb
spec:
  #type: LoadBalancer
  type: NodePort
  ports:
  - port: 443
    protocol: TCP
    name: https
    nodePort: 443
  selector:
    app: tbweb